In [2]:
import numpy as np
from numpy.linalg import inv, det
from numpy.linalg import solve
from numpy.linalg import norm

In [4]:
A = np.array([[1, 2],
              [3, -1]], float) # 2x2

B = np.array([[3, -2],
              [2,  1]], float) # 2x2

C = np.array([[1],
              [2],
              [3]], float)  # 3x1

D = np.array([[1, 3, 1],
              [-2, 1, -1]], float)  # 2x3

E = np.array([[3, 1],
              [0, 3],
              [-2, 2]], float)  # 3x2

F = np.array([[ 2, 1,  2],
              [-1, 3, -2]], float)  # 2x3

# Part A
print("Part A")
AB = A.dot(B)
print("AB = ", AB)

# CD: check
try:
    CD = C.dot(D)
    print("CD = ", CD)
except ValueError as e:
    print("CD not defined:", e)

EF = E.dot(F)
print("EF =\n", EF)

# Part B 
print("Part B")
ATB = A.T.dot(B)
print("A^T B = ", ATB)

# B D^T
try:
    BDT = B.dot(D.T)
    print("B D^T = ", BDT)
except ValueError as e:
    print("B D^T not defined:", e)

# D^T F^T
try:
    DTFT = D.T.dot(F.T)
    print("D^T F^T = ", DTFT)
except ValueError as e:
    print("D^T F^T not defined:", e)


Part A
AB =  [[ 7.  0.]
 [ 7. -7.]]
CD not defined: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)
EF =
 [[ 5.  6.  4.]
 [-3.  9. -6.]
 [-6.  4. -8.]]
Part B
A^T B =  [[ 9.  1.]
 [ 4. -5.]]
B D^T not defined: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)
D^T F^T not defined: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)


In [6]:
M = np.array([[1, 0, 1],
              [2, 2, 3],
              [1, 2, 4]], dtype=float)

print("Matrix M = ", M)

# Compute the inverse using NumPy
M_inv = inv(M)
print("Inverse of M (M^{-1}) = ", M_inv)

# Verify that M * M^{-1} = I and M^{-1} * M = I
print("M * M^{-1} = ", M.dot(M_inv))
print("M^{-1} * M = ", M_inv.dot(M))

Matrix M =  [[1. 0. 1.]
 [2. 2. 3.]
 [1. 2. 4.]]
Inverse of M (M^{-1}) =  [[ 0.5   0.5  -0.5 ]
 [-1.25  0.75 -0.25]
 [ 0.5  -0.5   0.5 ]]
M * M^{-1} =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M^{-1} * M =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
P = (1/7.0) * np.array([[3, -2, -6],
                        [-6, -3, -2],
                        [-2,  6, -3]], dtype=float)

# Transpose
PT = P.T

# Products to verify orthogonality
PPt = P.dot(PT)
PtP = PT.dot(P)

print("P = ", P)
print("P^T = ", PT)
print("P P^T = ", PPt)
print("P^T P = ", PtP)

# Numeric checks (True if orthogonal within numerical tolerance)
print("Is P orthogonal (P P^T == I)?", np.allclose(PPt, np.eye(3), atol=1e-10))
print("Is P orthogonal (P^T P == I)?", np.allclose(PtP, np.eye(3), atol=1e-10))

P =  [[ 0.42857143 -0.28571429 -0.85714286]
 [-0.85714286 -0.42857143 -0.28571429]
 [-0.28571429  0.85714286 -0.42857143]]
P^T =  [[ 0.42857143 -0.85714286 -0.28571429]
 [-0.28571429 -0.42857143  0.85714286]
 [-0.85714286 -0.28571429 -0.42857143]]
P P^T =  [[ 1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00 -1.38777878e-17]
 [ 0.00000000e+00 -1.38777878e-17  1.00000000e+00]]
P^T P =  [[ 1.00000000e+00  2.77555756e-17 -1.38777878e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  0.00000000e+00  1.00000000e+00]]
Is P orthogonal (P P^T == I)? True
Is P orthogonal (P^T P == I)? True


In [9]:
A = np.array([
    [-1,  3,  5,  2],
    [ 1,  9,  8,  4],
    [ 0,  1,  0,  1],
    [ 2,  1,  1, -1]
], dtype=float)

b = np.array([10, 15, 2, -3], dtype=float)

print("A = ", A)
print("b = ", b)

# Determinant check
detA = det(A)
print("det(A) = ", detA)

if abs(detA) < 1e-12:
    print("Determinant is (nearly) zero; the system may be singular or have infinite/no solutions.")
else:
    # Solve and verify
    x = solve(A, b)
    print("Solution x = [x1, x2, x3, x4]^T = ", x)

A =  [[-1.  3.  5.  2.]
 [ 1.  9.  8.  4.]
 [ 0.  1.  0.  1.]
 [ 2.  1.  1. -1.]]
b =  [10. 15.  2. -3.]
det(A) =  14.000000000000004
Solution x = [x1, x2, x3, x4]^T =  [-1.00000000e+00  7.31441052e-16  1.00000000e+00  2.00000000e+00]


In [17]:
A = np.array([[ 4, -1, -1,  0],
              [-1,  4,  0, -1],
              [-1,  0,  4, -1],
              [ 0, -1, -1,  4]], dtype=float)

b1 = np.array([1, 2, 0, 1], dtype=float)
b2 = np.array([4, 2, 10, -2], dtype=float)

# Gauss–Seidel function
def gauss_seidel(A, b, tol=1e-5, max_iter=10000):
    n = len(b)
    x = np.zeros(n)
    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - s1 - s2) / A[i, i]
        if np.linalg.norm(x - x_old, np.inf) < tol:
            return x    
    

# Call it 
x1 = gauss_seidel(A, b1)
x2 = gauss_seidel(A, b2)

print("For b1 =", b1)
print("x1 =", x1)
print("For b2 =", b2)
print("x2 =", x2)

For b1 = [1. 2. 0. 1.]
x1 = [0.49999857 0.74999928 0.24999928 0.49999964]
For b2 = [ 4.  2. 10. -2.]
x2 = [2.08333015 1.16666508 3.16666508 0.58333254]


In [18]:
A = np.array([[2, 2, 3],
              [1, 3, 9],
              [1, 6, 0]], dtype=float)

# Doolittle LU Decomposition
def lu_doolittle(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))
        for k in range(i + 1, n):
            L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]
    return L, U

# Perform LU decomposition
L, U = lu_doolittle(A)

print("L = ", L)
print("U = ", U)

# Determinant from LU
# Equation (4.102): det(A) = product of diagonal elements of U
det_A = np.prod(np.diag(U))
print("Determinant from LU decomposition = ", det_A)

# Inverse from LU
# Equation (4.99): solve A * X = I using LU factors
n = A.shape[0]
I = np.eye(n)
A_inv = np.zeros_like(A)

# Forward and backward substitution to get each column of A^-1
for col in range(n):
    e = I[:, col]

    # Forward solve: L y = e
    y = np.zeros(n)
    for i in range(n):
        y[i] = e[i] - np.dot(L[i, :i], y[:i])

    # Backward solve: U x = y
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]

    A_inv[:, col] = x

print("Inverse of A using LU decomposition = ", A_inv)

print("Check with np.linalg.inv(A): ", np.linalg.inv(A))
print("Check determinant with np.linalg.det(A): ", np.linalg.det(A))

L =  [[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 2.5 1. ]]
U =  [[  2.     2.     3.  ]
 [  0.     2.     7.5 ]
 [  0.     0.   -20.25]]
Determinant from LU decomposition =  -81.0
Inverse of A using LU decomposition =  [[ 0.66666667 -0.22222222 -0.11111111]
 [-0.11111111  0.03703704  0.18518519]
 [-0.03703704  0.12345679 -0.04938272]]
Check with np.linalg.inv(A):  [[ 0.66666667 -0.22222222 -0.11111111]
 [-0.11111111  0.03703704  0.18518519]
 [-0.03703704  0.12345679 -0.04938272]]
Check determinant with np.linalg.det(A):  -80.99999999999996


In [27]:
A = np.array([[0.780, 0.563],
               [0.913,0.659]], dtype=float)
b = np.array([0.217,0.254], dtype=float)
x_alpha = np.array([0.999, -1.001], dtype=float)
x_beta = np.array([0.341, -0.087], dtype=float)

r_alpha = b - A.dot(x_alpha)
r_beta = b - A.dot(x_beta)

print("Residual α =", r_alpha, "rα =", np.linalg.norm(r_alpha))
print("Residual β =", r_beta, "rβ = ", np.linalg.norm(r_beta)) 
# Not really. x_alpha is more accurate (closer to [1, -1])
print("det(A) = ", np.linalg.det(A))
# Determinant is very small, so A is nearly singular
print("Exact solution = ", np.linalg.solve(A, b))
# This confirms that x_alpha is much closer to the true solution than x_beta

Residual α = [0.001343 0.001572] rα = 0.0020675669275744828
Residual β = [1.e-06 0.e+00] rβ =  9.99999999945489e-07
det(A) =  1.000000000122681e-06
Exact solution =  [ 1. -1.]


In [34]:
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n), dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            raise ValueError("Matrix is rank deficient")
        Q[:, j] = v / R[j, j]

    return Q, R

# Example usage
A = np.array([[0.780, 0.563],
              [0.913, 0.659]], dtype=float)
b = np.array([0.217, 0.254], dtype=float)

# QR decomposition
Q, R = gram_schmidt(A)

# Compute Q^T b
y = np.dot(Q.T, b)

# Solve R x = y directly (since R is 2x2)
x = np.zeros_like(y)
x[1] = y[1] / R[1, 1]          # Solve for last variable
x[0] = (y[0] - R[0, 1]*x[1]) / R[0, 0]  # Solve for first variable

print("Solution x = ", x)
print("Residual b - A x = ", b - A @ x)

Solution x =  [ 1.00004295 -1.0000595 ]
Residual b - A x =  [-3.76749465e-11  3.21864757e-11]
