In [14]:
import numpy as np
from numpy.linalg import inv, det
from numpy.linalg import solve
from numpy.linalg import norm

In [15]:
A = np.array([[1,2],[3,-1]], dtype=float)
B = np.array([[3,-2],[2,1]], dtype=float)
C = np.array([[1],[2],[3]], dtype=float)
D = np.array([[1,3,1],[-2,1,-1]], dtype=float)
E = np.array([[3,1],[0,3],[-2,2]], dtype=float)
F = np.array([[2,1,2],[-1,3,-2]], dtype=float)

# A) Products
AB = A.dot(B)
print("AB =\n", AB)

try:
    CD = C.dot(D)
except Exception as e:
    print("CD not defined:", e)

DC = D.dot(C)
print("D*C =\n", DC)
EF = E.dot(F)
print("EF =\n", EF)

# B) Products with transposes
ATB = A.T.dot(B)
print("A^T * B =\n", ATB)

try:
    BDT = B.dot(D.T)
except Exception as e:
    print("B*D^T not defined:", e)

try:
    DTFT = D.T.dot(F.T)
except Exception as e:
    print("D^T * F^T not defined:", e)


AB =
 [[ 7.  0.]
 [ 7. -7.]]
CD not defined: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)
D*C =
 [[10.]
 [-3.]]
EF =
 [[ 5.  6.  4.]
 [-3.  9. -6.]
 [-6.  4. -8.]]
A^T * B =
 [[ 9.  1.]
 [ 4. -5.]]
B*D^T not defined: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)
D^T * F^T not defined: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)


In [16]:
M = np.array([[1,0,1],[2,2,3],[1,2,4]], dtype=float)
M_inv = inv(M)
print("M^-1 =\n", M_inv)
print("M * M^-1 =\n", M.dot(M_inv))
print("det(M) =", det(M))

M^-1 =
 [[ 0.5   0.5  -0.5 ]
 [-1.25  0.75 -0.25]
 [ 0.5  -0.5   0.5 ]]
M * M^-1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det(M) = 4.0


In [17]:
P = (1/7.0) * np.array([[3,-2,-6],[-6,-3,-2],[-2,6,-3]], dtype=float)
PT = P.T
print("P^T * P =\n", PT.dot(P))
print("P * P^T =\n", P.dot(PT))
print("Is P orthogonal?", np.allclose(P.dot(PT), np.eye(3)))


P^T * P =
 [[ 1.00000000e+00  2.77555756e-17 -1.38777878e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  0.00000000e+00  1.00000000e+00]]
P * P^T =
 [[ 1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00 -1.38777878e-17]
 [ 0.00000000e+00 -1.38777878e-17  1.00000000e+00]]
Is P orthogonal? True


In [18]:
A4 = np.array([[-1,3,5,2],[1,9,8,4],[0,1,0,1],[2,1,1,-1]], dtype=float)
b4 = np.array([10,15,2,-3], dtype=float)
detA4 = det(A4)
print("det(A4) =", detA4)
x4 = solve(A4, b4)
print("Solution x =", x4)

det(A4) = 14.000000000000004
Solution x = [-1.00000000e+00  7.31441052e-16  1.00000000e+00  2.00000000e+00]


In [19]:
A5 = np.array([[4,-1,-1,0],[-1,4,0,-1],[-1,0,4,-1],[0,-1,-1,4]], dtype=float)
b5a = np.array([1,2,0,1], dtype=float)
b5b = np.array([4,2,10,-2], dtype=float)

def gauss_seidel(A, b, tol=1e-5, maxiter=10000):
    n = len(b)
    x = np.zeros(n)
    for k in range(maxiter):
        x_old = x.copy()
        for i in range(n):
            s1 = np.dot(A[i,:i], x[:i])
            s2 = np.dot(A[i,i+1:], x_old[i+1:])
            x[i] = (b[i] - s1 - s2) / A[i,i]
        if norm(x - x_old, np.inf) < tol:
            return x, k+1
    return x, maxiter

x5a, iters_a = gauss_seidel(A5, b5a)
x5b, iters_b = gauss_seidel(A5, b5b)
print("b =", b5a, "=> x =", x5a, "in", iters_a, "iterations")
print("b =", b5b, "=> x =", x5b, "in", iters_b, "iterations")

b = [1. 2. 0. 1.] => x = [0.49999857 0.74999928 0.24999928 0.49999964] in 10 iterations
b = [ 4.  2. 10. -2.] => x = [2.08333015 1.16666508 3.16666508 0.58333254] in 10 iterations


In [20]:
def lu_doolittle(A):
    A = A.astype(float)
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n,n))
    for i in range(n):
        for k in range(i, n):
            U[i,k] = A[i,k] - sum(L[i,j]*U[j,k] for j in range(i))
        for k in range(i+1, n):
            L[k,i] = (A[k,i] - sum(L[k,j]*U[j,i] for j in range(i))) / U[i,i]
    return L, U

A6 = np.array([[4,3,2],[3,2,1],[2,1,3]], dtype=float)
L6, U6 = lu_doolittle(A6)
print("L =\n", L6)
print("U =\n", U6)
print("det(A) =", np.prod(np.diag(U6)), "vs numpy:", det(A6))

L =
 [[1.   0.   0.  ]
 [0.75 1.   0.  ]
 [0.5  2.   1.  ]]
U =
 [[ 4.    3.    2.  ]
 [ 0.   -0.25 -0.5 ]
 [ 0.    0.    3.  ]]
det(A) = -3.0 vs numpy: -2.9999999999999996


In [21]:
A7 = np.array([[0.780, 0.563],[0.913,0.659]], dtype=float)
b7 = np.array([0.217,0.254], dtype=float)
x_alpha = np.array([0.999, -1.001], dtype=float)
x_beta = np.array([0.341, -0.087], dtype=float)

r_alpha = b7 - A7.dot(x_alpha)
r_beta = b7 - A7.dot(x_beta)

print("Residual α =", r_alpha, "||rα|| =", np.linalg.norm(r_alpha))
print("Residual β =", r_beta, "||rβ|| =", np.linalg.norm(r_beta))
print("det(A) =", det(A7))
print("Exact solution =", np.linalg.solve(A7,b7))

Residual α = [0.001343 0.001572] ||rα|| = 0.0020675669275744828
Residual β = [1.e-06 0.e+00] ||rβ|| = 9.99999999945489e-07
det(A) = 1.000000000122681e-06
Exact solution = [ 1. -1.]


In [22]:
def classical_gram_schmidt(A):
    A = A.astype(float)
    m, n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for j in range(n):
        v = A[:,j].copy()
        for i in range(j):
            R[i,j] = Q[:,i].dot(A[:,j])
            v = v - R[i,j]*Q[:,i]
        R[j,j] = norm(v)
        Q[:,j] = v / R[j,j] if R[j,j] != 0 else v
    return Q, R

A8 = np.array([[3., -1., 2.],[2., 0., -1.],[1., 4., 3.]])
b8 = np.array([1., 2., 3.])
Q8, R8 = classical_gram_schmidt(A8)
x_qr = solve(R8, Q8.T.dot(b8))
x_direct = solve(A8, b8)
print("A8:\n", A8)
print("Q8:\n", Q8)
print("R8:\n", R8)
print("x from QR:", x_qr)
print("x direct:", x_direct)
print("Are they close?:", np.allclose(x_qr, x_direct))

A8:
 [[ 3. -1.  2.]
 [ 2.  0. -1.]
 [ 1.  4.  3.]]
Q8:
 [[ 0.80178373 -0.29512821  0.51965584]
 [ 0.53452248 -0.03472097 -0.84444074]
 [ 0.26726124  0.95482658  0.12991396]]
R8:
 [[3.74165739 0.26726124 1.87082869]
 [0.         4.11443452 2.30894427]
 [0.         0.         2.27349431]]
x from QR: [ 0.82857143  0.8        -0.34285714]
x direct: [ 0.82857143  0.8        -0.34285714]
Are they close?: True


In [23]:
i = 1j
Mx = (1/np.sqrt(2)) * np.array([[0,1,0],[1,0,1],[0,1,0]], dtype=complex)
My = (1/np.sqrt(2)) * np.array([[0,-i,0],[i,0,-i],[0,i,0]], dtype=complex)
Mz = np.array([[1,0,0],[0,0,0],[0,0,-1]], dtype=complex)
print("Mx:\n", Mx)
print("My:\n", My)
print("Mz:\n", Mz)

comm_xy = Mx.dot(My) - My.dot(Mx)
print("[Mx,My]:\n", comm_xy)
print("i * Mz:\n", i*Mz)
print("Check [Mx,My] ~ i Mz?:", np.allclose(comm_xy, i*Mz))

comm_yz = My.dot(Mz) - Mz.dot(My)
print("[My,Mz] ?= i Mx :", np.allclose(comm_yz, i*Mx))
comm_zx = Mz.dot(Mx) - Mx.dot(Mz)
print("[Mz,Mx] ?= i My :", np.allclose(comm_zx, i*My))

M2 = Mx.dot(Mx) + My.dot(My) + Mz.dot(Mz)
print("M^2 (Mx^2 + My^2 + Mz^2):\n", M2)
print("2 * I:\n", 2*np.eye(3))
print("Check M^2 == 2I?:", np.allclose(M2, 2*np.eye(3)))

Lp = Mx + i*My
Lm = Mx - i*My
comm_LpLm = Lp.dot(Lm) - Lm.dot(Lp)
print("[L+, L-]:\n", comm_LpLm)
print("2 Mz:\n", 2*Mz)
print("Check [L+,L-] == 2Mz?:", np.allclose(comm_LpLm, 2*Mz))

Mx:
 [[0.        +0.j 0.70710678+0.j 0.        +0.j]
 [0.70710678+0.j 0.        +0.j 0.70710678+0.j]
 [0.        +0.j 0.70710678+0.j 0.        +0.j]]
My:
 [[0.+0.j         0.-0.70710678j 0.+0.j        ]
 [0.+0.70710678j 0.+0.j         0.-0.70710678j]
 [0.+0.j         0.+0.70710678j 0.+0.j        ]]
Mz:
 [[ 1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j]]
[Mx,My]:
 [[0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j]]
i * Mz:
 [[ 0.+1.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -0.-1.j]]
Check [Mx,My] ~ i Mz?: True
[My,Mz] ?= i Mx : True
[Mz,Mx] ?= i My : True
M^2 (Mx^2 + My^2 + Mz^2):
 [[2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j]]
2 * I:
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Check M^2 == 2I?: True
[L+, L-]:
 [[ 2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j]]
2 Mz:
 [[ 2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j]]
Check [L+,L-] =

In [24]:
Lp_simple = np.array([[0,1,0],[0,0,1],[0,0,0]], dtype=float)
Lm_simple = np.array([[0,0,0],[1,0,0],[0,1,0]], dtype=float)
ket_m1 = np.array([0,0,1], dtype=float)
ket_0  = np.array([0,1,0], dtype=float)
ket_p1 = np.array([1,0,0], dtype=float)

print("L+:\n", Lp_simple)
print("L-:\n", Lm_simple)
print("L+ | -1> =", Lp_simple.dot(ket_m1))
print("L- | -1> =", Lm_simple.dot(ket_m1))
print("L+ | 0> =", Lp_simple.dot(ket_0))
print("L- | 0> =", Lm_simple.dot(ket_0))
print("L+ | 1> =", Lp_simple.dot(ket_p1))
print("L- | 1> =", Lm_simple.dot(ket_p1))

L+:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
L-:
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
L+ | -1> = [0. 1. 0.]
L- | -1> = [0. 0. 0.]
L+ | 0> = [1. 0. 0.]
L- | 0> = [0. 0. 1.]
L+ | 1> = [0. 0. 0.]
L- | 1> = [0. 1. 0.]
